# create pod.yaml file with configmap,loadbalanceer,nodepaort, deployment.yaml and secret volume mounts
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
containers:
    - name: my-container
      image: my-image:latest
      ports:
        - containerPort: 8080
        - containerPort: 8443
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secrets
      volumes:
    - name: config-volume
      configMap:
        name: my-config
    - name: secret-volume
      secret:
        secretName: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 443
      targetPort: 8443
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8443
      targetPort: 8443
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:

  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment